### ISSUE TITLE
is this indentation correct?

### ISSUE THREAD

**Issue by jedahan** [evbogue/mvd#3]
https://github.com/evbogue/mvd/blob/392e50fcc67f4ad4b873fc95b096e3018404f255/render.js#L164

do you mean this line to always be evaluated?

**Comment by evbogue** [comment]
Sorry, I wasn't watching my own project so I didn't see this!

Yes, the indentation is correct. `original` always points back to the first message that you edited. The idea is to keep a record of the original un-edited message, just in case you want to diff against the original message after it's been edited more than one time.

**Comment by jedahan** [comment]
Sounds good to me. Not sure if its a style thing but i'd love to see that line un-indented or the previous line wrapped `{}` but its not a broken thing so closing for now.

**Comment by jedahan** [comment]
I mean not to start a whole bikeshed but I usually just run prettier-standard

**Comment by evbogue** [comment]
@jedahan I'm just happy that it works!
